# Netlify 배포 설정
[build]
  publish = "dist"
  command = "npm run build:prod"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# SPA를 위한 라우팅 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 정적 파일 캐싱 설정
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# PWA 매니페스트 및 아이콘 캐싱
[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/icon*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# 보안 헤더
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
